version: '3.8'

services:
  onlyoffice:
    # Cambiamos a la versión sin límites
    image: ghcr.io/thomisus/onlyoffice-documentserver-unlimited:latest
    container_name: onlyofficeVS
    restart: always
    privileged: true
    ports:
      - "8085:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=secreto_personalizado
      - JWT_HEADER=Authorization
    # NOTA: Si ya tenías datos en el contenedor anterior, 
    # se borrarán al cambiar la imagen a menos que uses volúmenes.
    # volumes:
    #   - ./onlyoffice/logs:/var/log/onlyoffice
    #   - ./onlyoffice/data:/var/www/onlyoffice/Data
    #   - ./onlyoffice/lib:/var/lib/onlyoffice
    #   - ./onlyoffice/db:/var/lib/postgresql